const translations = {
    en: {
      restaurantName: "PizzaPizza",
      signup: "Sign Up",
      email: "Email *",
      password: "Password *",
      confirmPassword: "Password (repeat) *",
      firstName: "Name *",
      lastName: "Last name *",
      phoneNumber: "Phone Number",
      postalCode: "Postal code *",
      address: "Address",
      house: "House *",
      stairs: "Stairs (optional)",
      stick: "Stick (optional)",
      door: "Door",
      bell: "Bell (optional)",
      comment: "Comment on your address (optional)",
      agreeTerms: "I agree to the terms and conditions.",
      reset: "Reset",
      cancel: "Cancel",
      addToBasket: "Add to basket",
      searchMenu: "Search in Menu",
      close: "Close",
      forgotPassword: "Forgot password?",
      logout: "Log Out",
      proceedToCheckout: "Review payment and address",
      total: "Total",
      basketEmpty: "Your basket is empty",
      yourBasket: "Your Items",
      basketSummary: "Summary",
      basketUpdatedCouponRemoved: "Your basket has been updated and the coupon has been removed",
      checkout: {
        title: "Checkout",
        backToOrder: "Back to Order",
        orderSummary: "Order Summary",
        paymentMethod: "Payment Method",
        creditCard: "Credit Card",
        payWithStripe: "Pay with Stripe",
        cash: "Cash",
        payOnDelivery: "Pay on delivery",
        payOnPickup: "Pay on pickup",
        secure: "Secure",
        minimumOrderValue: "Minimum order value",
        minimumOrderNotMet: "Add more items to meet the minimum order value",
        enterCouponCode: "Enter coupon code",
        couponApplied: "Coupon already applied",
        validating: "Validating...",
        apply: "Apply",
        processing: "Processing...",
        agreeToTerms: "I agree to the ",
        termsAndConditions: "terms and conditions",
        specialNotesPlaceholder: "Enter any special delivery instructions or additional information...",
        easy: "Easy",
        total: "Total",
        orderDetails: "Order Details",
        deliveryAddress: "Delivery Address",
        contactInfo: "Contact Information",
        email: "Email",
        phone: "Phone",
        specialNotes: "Special Notes",
        paymentDetails: "Payment Details",
        orderTotal: "Order Total",
        originalPrice: "Original Price",
        discountedPrice: "Discounted Price",
        completeOrder: "Complete Order",
        loading: "Loading...",
        error: {
          fetchingPostcodes: "Error fetching postcodes",
          fetchingAddresses: "Error fetching addresses",
          invalidEmail: "Please enter a valid email address",
          invalidPhone: "Please enter a valid phone number",
          termsRequired: "Please accept the terms and conditions",
          paymentRequired: "Please select a payment method",
          addressRequired: "Please enter a delivery address",
          general: "An error occurred. Please try again."
        },
        invalidCoupon: "Invalid coupon code",
        emailRequired: "Please enter your email address before applying a coupon"
      },
      orderMethod: "Order Method",
      delivery: "Delivery",
      selfCollection: "Pickup",
      phone: "Phone *",
      specialNotes: "Special Notes (Optional)",
      completeOrder: "Complete Order",
      totalAmount: "Total Amount",
      homePageTitle: "Welcome to Our Restaurant",
      welcomeMessage: "Welcome to Pizza Vienna ",
      welcomeText:
        "At Pizza Vienna, we serve more than just food — we serve the best culinary experience in town. Our menu is crafted with passion, featuring a wide selection of delicious, handcrafted dishes made from the freshest, high-quality ingredients.",
      contactUs: "Feel free to explore our menu or contact us for any inquiries.",
      optional: "optional",
      restaurantDescription: "Come and try our delicious menu!",
      orderNow:"Order Now",
      visitUs: "Visit Us",
      openingHours: "Opening Hours",
      openDaily: "Open Daily",
      contact: "Contact",
      location: "Location",
      paymentSuccess: {
        title: "Payment Successful!",
        loading: "Loading...",
        error: "Error",
        completed: "Payment Completed",
        processing: "Payment Processing",
        pending: "Payment Pending",
        unknown: "Unknown Status",
        cashPending: "Order Pending - Pay at Pickup",
        orderDetails: "Order Details",
        orderNumber: "Order Number",
        total: "Total",
        paymentMethod: "Payment Method",
        orderMore: "Order More",
        returnHome: "Return to Home"
      },
      promotions: "Promotions",
      free: "Free",
      specialInstructions: "Special Instructions",
      addNote: "Add any special instructions or notes...",
      selectedOptions: "Selected Options",
      note: "Note",
      hideInfo: "Hide Info",
      info: "Info"
    }, 
    tr: {
      restaurantName: "PizzaPizza",
      signup: "Kayıt Ol",
      email: "E-posta *",
      password: "Şifre *",
      confirmPassword: "Şifreyi Tekrarla *",
      firstName: "Ad *",
      lastName: "Soyad *",
      phoneNumber: "Telefon numarası *",
      postalCode: "Posta kodu *",
      address: "Adres *",
      house: "Ev *",
      stairs: "Kat (isteğe bağlı)",
      stick: "Sopa (isteğe bağlı)",
      door: "Kapı",
      bell: "Zil (isteğe bağlı)",
      comment: "Yorum (isteğe bağlı)",
      agreeTerms: "Şartlar ve koşulları kabul ediyorum.",
      reset: "Sıfırla",
      cancel: "İptal",
      addToBasket: "Sepete Ekle",
      searchMenu: "Menüde Ara",
      basketSummary: "Özet",
      close: "Kapat",
      forgotPassword: "Şifremi unuttum?",
      logout: "Çıkış Yap",
      proceedToCheckout: "Sepeti Onayla",
      total: "Toplam",
      basketEmpty: "Sepetiniz boş",
      yourBasket: "Ürünleriniz",
      basketUpdatedCouponRemoved: "Sepetiniz güncellendi ve kupon kaldırıldı",
      checkout: {
        title: "Ödeme",
        backToOrder: "Siparişe Geri Dön",
        orderSummary: "Sipariş Özeti",
        paymentMethod: "Ödeme Yöntemi",
        creditCard: "Kredi Kartı",
        payWithStripe: "Stripe ile Öde",
        cash: "Nakit",
        payOnDelivery: "Teslimatta öde",
        payOnPickup: "Gel-Al'da öde",
        secure: "Güvenli",
        minimumOrderValue: "Minimum sipariş tutarı",
        minimumOrderNotMet: "Minimum sipariş tutarını karşılamak için daha fazla ürün ekleyin",
        enterCouponCode: "Kupon kodunu girin",
        couponApplied: "Kupon zaten uygulandı",
        validating: "Doğrulanıyor...",
        apply: "Uygula",
        processing: "İşleniyor...",
        agreeToTerms: "Kabul ediyorum ",
        termsAndConditions: "şartlar ve koşullar",
        specialNotesPlaceholder: "Özel teslimat talimatları veya ek bilgiler girin...",
        easy: "Kolay",
        total: "Toplam",
        orderDetails: "Sipariş Detayları",
        deliveryAddress: "Teslimat Adresi",
        contactInfo: "İletişim Bilgileri",
        email: "E-posta",
        phone: "Telefon",
        specialNotes: "Özel Notlar",
        paymentDetails: "Ödeme Detayları",
        orderTotal: "Sipariş Toplamı",
        originalPrice: "Orijinal Fiyat",
        discountedPrice: "İndirimli Fiyat",
        completeOrder: "Siparişi Tamamla",
        loading: "Yükleniyor...",
        error: {
          fetchingPostcodes: "Posta kodları alınırken hata oluştu",
          fetchingAddresses: "Adresler alınırken hata oluştu",
          invalidEmail: "Lütfen geçerli bir e-posta adresi girin",
          invalidPhone: "Lütfen geçerli bir telefon numarası girin",
          termsRequired: "Lütfen şartları ve koşulları kabul edin",
          paymentRequired: "Lütfen bir ödeme yöntemi seçin",
          addressRequired: "Lütfen bir teslimat adresi girin",
          general: "Bir hata oluştu. Lütfen tekrar deneyin."
        },
        invalidCoupon: "Geçersiz kupon kodu",
        emailRequired: "Lütfen kupon uygulamadan önce e-posta adresinizi girin"
      },
      orderMethod: "Sipariş Yöntemi",
      delivery: "Teslimat",
      selfCollection: "Gel-Al ",
      phone: "Telefon *",
      specialNotes: "Özel Notlar (Opsiyonel)",
      completeOrder: "Siparişi Tamamla",
      totalAmount: "Toplam Miktar",
      welcomeMessage: "Pizza Vienna'ya Hoşgeldiniz",
      welcomeText:
        "Pizza Vienna'da sadece yemek değil, aynı zamanda şehrin en iyi mutfak deneyimini sunuyoruz. Menümüz, taze ve kaliteli malzemelerle hazırlanmış, özenle seçilmiş el yapımı lezzetlerle doludur.",
      contactUs: "Menümüzü keşfetmekten veya bizimle iletişime geçmekten çekinmeyin.",
      optional: "isteğe bağlı",
      summary:"Sipariş Özeti",
      orderNow:"Sipariş Ver",
      visitUs: "Bizi Ziyaret Edin",
      openingHours: "Çalışma Saatleri",
      openDaily: "Her Gün Açık",
      contact: "İletişim",
      phoneNumber: "+43 123 456 789",
      location: "Konum",
      address: "Viyana, Avusturya",
      paymentSuccess: {
        title: "Ödeme Başarılı!",
        loading: "Yükleniyor...",
        error: "Hata",
        completed: "Ödeme Tamamlandı",
        processing: "Ödeme İşleniyor",
        pending: "Ödeme Beklemede",
        unknown: "Bilinmeyen Durum",
        cashPending: "Sipariş Beklemede - Teslimatta Ödeyin",
        orderDetails: "Sipariş Detayları",
        orderNumber: "Sipariş Numarası",
        total: "Toplam",
        paymentMethod: "Ödeme Yöntemi",
        orderMore: "Tekrar Sipariş Ver",
        returnHome: "Ana Sayfaya Dön"
      },
      promotions: "Kampanyalar",
      free: "Ücretsiz",
      specialInstructions: "Özel Talimatlar",
      addNote: "Özel talimat veya not ekleyin...",
      selectedOptions: "Seçilen Seçenekler",
      note: "Not",
      hideInfo: "Bilgiyi Gizle",
      info: "Bilgi"
    },
    de: {
      phoneNumber: 'Telefonnummer',
      address: 'Adresse',
    }
  };
  
  export default translations;
  